version: '2'
services:
  web:
    image: playbackpro-web
#    build: ./web
#    volumes:
#    - ./web/src:/app
    ports:
    - "8000:80"
    links:
    - proxy
  proxy:
    image: websockify
#    build: ./proxy
    expose:
    - "8081"
    command: ["8081", "--token-plugin", "tokenpass.TokenPassPlugin"]
